name: bench

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MIX_ENV: bench

    strategy:
      matrix:
        elixir: [1.17]
        otp: [27]

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: bench-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.head_ref || github.ref }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            bench-${{ matrix.otp }}-${{ matrix.elixir }}-${{ github.head_ref || github.ref }}-
            bench-${{ matrix.otp }}-${{ matrix.elixir }}-refs/heads/master-

      - name: 🦆💿 INSTALLING DUCKDB (QUACK QUACK) 🦆💿
        env:
          DUCKDB_VERSION: v1.1.3
          DUCKDB_ARCH: amd64
        run: |
          curl -L https://github.com/duckdb/duckdb/releases/download/${DUCKDB_VERSION}/libduckdb-linux-${DUCKDB_ARCH}.zip -o libduckdb.zip
          unzip libduckdb.zip -d libduckdb

      - run: mix deps.get --only $MIX_ENV
      - run: V=1 DUXDB_LDFLAGS="-L$(pwd)/libduckdb -Wl,-rpath=$(pwd)/libduckdb" mix compile --warnings-as-errors
      - run: mix run bench/fetch_all.exs
